const express = require('express');
const router = express.Router();
const Order = require('../models/Order');

// GET all orders
router.get('/', async (req, res) => {
  try {
    const { status, tableNumber } = req.query;
    let query = {};
    
    if (status) query.status = status;
    if (tableNumber) query.tableNumber = tableNumber;
    
    const orders = await Order.find(query)
      .populate('items.menuItem', 'name price image')
      .sort({ createdAt: -1 });
    res.json(orders);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// GET single order
router.get('/:id', async (req, res) => {
  try {
    const order = await Order.findById(req.params.id)
      .populate('items.menuItem', 'name price image');
    if (!order) {
      return res.status(404).json({ message: 'Order not found' });
    }
    res.json(order);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// POST create new order
router.post('/', async (req, res) => {
  try {
    console.log('Creating order with data:', req.body);

    // Validate required fields
    if (!req.body.tableNumber) {
      return res.status(400).json({ message: 'Table number is required' });
    }
    if (!req.body.items || req.body.items.length === 0) {
      return res.status(400).json({ message: 'Order must contain at least one item' });
    }
    if (!req.body.totalAmount) {
      return res.status(400).json({ message: 'Total amount is required' });
    }

    // Create order without orderNumber - it will be generated by the pre-save hook
    const order = new Order(req.body);
    const savedOrder = await order.save();
    const populatedOrder = await Order.findById(savedOrder._id)
      .populate('items.menuItem', 'name price image');

    console.log('Order created successfully:', populatedOrder.orderNumber);

    // Emit real-time notification to ALL connected clients
    const io = req.app.get('io');
    io.emit('new-order', populatedOrder);

    res.status(201).json(populatedOrder);
  } catch (error) {
    console.error('Error creating order:', error);
    res.status(400).json({ message: error.message, details: error.errors || error });
  }
});

// PUT update order status
router.put('/:id/status', async (req, res) => {
  try {
    const { status } = req.body;
    const order = await Order.findByIdAndUpdate(
      req.params.id,
      { status },
      { new: true, runValidators: true }
    ).populate('items.menuItem', 'name price image');
    
    if (!order) {
      return res.status(404).json({ message: 'Order not found' });
    }
    
    // Emit real-time status update to ALL connected clients
    const io = req.app.get('io');
    io.emit('order-status-updated', order);

    res.json(order);
  } catch (error) {
    res.status(400).json({ message: error.message });
  }
});

// PUT update entire order
router.put('/:id', async (req, res) => {
  try {
    const order = await Order.findByIdAndUpdate(
      req.params.id,
      req.body,
      { new: true, runValidators: true }
    ).populate('items.menuItem', 'name price image');
    
    if (!order) {
      return res.status(404).json({ message: 'Order not found' });
    }
    
    // Emit real-time update to ALL connected clients
    const io = req.app.get('io');
    io.emit('order-updated', order);

    res.json(order);
  } catch (error) {
    res.status(400).json({ message: error.message });
  }
});

// DELETE order
router.delete('/:id', async (req, res) => {
  try {
    const order = await Order.findByIdAndUpdate(
      req.params.id,
      { status: 'cancelled' },
      { new: true }
    );
    if (!order) {
      return res.status(404).json({ message: 'Order not found' });
    }

    // Emit real-time cancellation to ALL connected clients
    const io = req.app.get('io');
    io.emit('order-cancelled', order);

    res.json({ message: 'Order cancelled successfully' });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// DELETE all orders for a table
router.delete('/table/:tableNumber', async (req, res) => {
  try {
    const { tableNumber } = req.params;
    const result = await Order.deleteMany({ tableNumber });

    // Emit real-time update to ALL connected clients
    const io = req.app.get('io');
    io.emit('table-orders-cleared', { tableNumber });

    res.json({ message: `Cleared ${result.deletedCount} orders for table ${tableNumber}` });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// DELETE all orders
router.delete('/clear-all/all', async (req, res) => {
  try {
    const result = await Order.deleteMany({});

    // Emit real-time update to ALL connected clients
    const io = req.app.get('io');
    io.emit('all-orders-cleared', { deletedCount: result.deletedCount });

    res.json({ message: `Cleared ${result.deletedCount} orders successfully` });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// POST reset order counter (admin only)
router.post('/admin/reset-counter', async (req, res) => {
  try {
    const Counter = require('../models/Counter');
    const { startValue = 0 } = req.body;

    // Reset the counter to the specified start value
    await Counter.findByIdAndUpdate(
      'orderNumber',
      { sequence_value: startValue },
      { new: true, upsert: true }
    );

    res.json({ message: `Order counter reset to ${startValue}` });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

module.exports = router;
